# /03-files-sync/docker-compose.yml
#
# SyncThing Stack
# Purpose: Provides decentralized, continuous file synchronization.
# Uses host networking for better peer discovery/NAT traversal.
# Relies on variables from ../.env and host directory bind mounts.
# Web UI is typically exposed via Caddy proxying to localhost:8384.

version: '3.8'

services:
  syncthing:
    # Pinning version recommended. Check SyncThing releases.
    image: syncthing/syncthing:1.27.7 # Or use :latest
    container_name: syncthing
    hostname: syncthing-docker # Optional: Set a specific hostname visible within SyncThing UI/logs
    restart: unless-stopped
    env_file:
      - ../.env # Load PUID, PGID, TZ from root .env file

    # --- Host Networking ---
    # Connects container directly to the host's network stack.
    # Simplifies peer discovery but reduces isolation and uses host ports directly.
    # Ensure ports 8384, 22000 (TCP/UDP), 21027 (UDP) are free on the host.
    network_mode: host

    environment:
      # Values sourced from ../.env via env_file:
      # CRITICAL: These MUST match the owner of the host directories below.
      - PUID=${SYNCTHING_PUID:-1000}
      - PGID=${SYNCTHING_PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
      # Optional: Set Syncthing's home directory if needed (usually defaults correctly)
      # - STHOME=/var/syncthing/config

    volumes:
      # --- Host Bind Mounts (CRITICAL) ---
      # You MUST create these directories on the host first AND ensure
      # they are owned by the user/group specified by PUID/PGID above.
      # Map host config directory to container's config location
      - ./syncthing_config:/var/syncthing/config
      # Map host data directory root to container's sync root
      # Inside SyncThing UI, configure folders relative to '/var/syncthing/Sync'
      - ./syncthing_data:/var/syncthing/Sync
      # Example: Add more distinct host folders if needed
      # - /path/to/host/photos:/var/syncthing/Photos # Absolute path example

    # Ports section is informative when using network_mode: host,
    # as the container uses the host ports directly.
    ports:
      - "8384:8384"   # Web UI (Accessed via localhost:8384 by Caddy)
      - "22000:22000/tcp" # TCP Sync Protocol
      - "22000:22000/udp" # QUIC Sync Protocol
      - "21027:21027/udp" # Discovery Broadcasts

    # Optional: Add resource limits if needed
    deploy:
      resources:
        limits:
          memory: 2G

# Volumes section is not strictly necessary here as we are using bind mounts,
# but defining them explicitly doesn't hurt if you mix strategies later.
# volumes: {}

# Networks section is not used for the 'syncthing' service itself
# because it uses network_mode: host.
# networks: {}
