# /01-management/docker-compose.yml

# Komodo Management & Homarr Homepage Stack
# Purpose: Provides a web UI for managing Docker stacks and deployments.

services:
  komodo:
    image: komodo/komodo-core:latest
    container_name: komodo
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - komodo_data:/app/data 
    networks:
      - proxy_network
    ports:
      - "9443:9443"
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - /var/run/docker.sock:var/run/docker.sock
      - ./homarr/appdata:/appdata
    networks:
      - proxy_network
    environment:
      - SECRET_ENCRYPTION_KEY={$HOMARR_KEY}
    ports:
      - "7575:7575"

volumes:
  komodo_data:
    driver: local

networks:
  proxy_network:
    external: true
    name: proxy_network
