# /01-management/docker-compose.yml

# Komodo Management Stack
# Purpose: Provides a web UI for managing Docker stacks and deployments.

services:
  komodo:
    image: komodo/komodo-core:latest
    container_name: komodo
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - komodo_data:/app/data 
    networks:
      - proxy_network
    ports:
      - "9443:9443"

volumes:
  komodo_data:
    driver: local

networks:
  proxy_network:
    external: true
    name: proxy_network
