# /00-proxy/docker-compose.yml
#
# Caddy Reverse Proxy Stack
# Purpose: Acts as the main entry point, handles HTTPS, and routes traffic.
# Uses Cloudflare DNS plugin for ACME challenges.
# Relies on shared 'proxy_network' and variables from ../.env

# version: '3.8'

services:
  caddy:
    # Use an image WITH the Cloudflare plugin. Pinning version is recommended.
    # Check https://github.com/caddy-dns/cloudflare#docker-hub for image details
    # Example using ghcr.io build:
    image: ghcr.io/caddybuilds/caddy-cloudflare:latest # Or use :latest if preferred
    container_name: caddy
    restart: unless-stopped
    env_file:
      - ../.env # Load variables from the root .env file

    ports:
      # Essential ports for web traffic - MUST be exposed on host
      - "80:80"       # HTTP
      - "443:443"     # HTTPS
      - "443:443/udp" # HTTP/3 (QUIC)

    volumes:
      # Bind mount the Caddyfile from this directory
      - ./Caddyfile:/etc/caddy/Caddyfile:ro # Mount config read-only
      # Optional: Bind mount for serving static files directly
      # Create './site' directory if you uncomment this
      # - ./site:/srv
      # Named volumes for persistent Caddy state (certs, etc.) and config backups
      - caddy_data:/data
      - caddy_config:/config

    environment:
      # Variables needed by Caddy (values sourced from ../.env via env_file)
      # Ensure these variable names EXACTLY match your ../.env file:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - ACME_EMAIL=${ACME_EMAIL}
      - TZ=${TZ:-Etc/UTC} # Use TZ from .env, default to UTC

    networks:
      # Connect to the shared external proxy network
      - proxy_network

    cap_add:
      # Required to bind ports 80/443 as non-root user inside container
      - NET_BIND_SERVICE

# Define the named volumes used by this service
volumes:
  caddy_data:
    driver: local # Or specify another driver if needed
  caddy_config:
    driver: local

# Define the shared network used by this service as external
networks:
  proxy_network:
    external: true
    name: proxy_network # Optional: Explicitly name it if it differs from the key
