# /00-proxy/docker-compose.yml
#
# Caddy Reverse Proxy Stack
# Purpose: Acts as the main entry point, handles HTTPS, and routes traffic.
# Uses Cloudflare DNS plugin for ACME challenges.
# Relies on shared 'proxy_network' and variables from ../.env

# version: '3.8'

services:
  caddy:
    # Use an image WITH the Cloudflare plugin. Pinning version is recommended.
    # Check https://github.com/caddy-dns/cloudflare#docker-hub for image details
    # Example using ghcr.io build:
    image: ghcr.io/caddybuilds/caddy-cloudflare:latest # Or use :latest if preferred
    container_name: caddy
    restart: unless-stopped
    env_file:
      - ../.env # Load variables from the root .env file

    ports:
      # Essential ports for web traffic - MUST be exposed on host
      - "80:80"       # HTTP
      - "443:443"     # HTTPS
      - "443:443/udp" # HTTP/3 (QUIC)

    volumes:
      # Bind mount the Caddyfile from this directory
      - ./Caddyfile:/etc/caddy/Caddyfile:ro # Mount config read-only
      # Optional: Bind mount for serving static files directly
      # Create './site' directory if you uncomment this
      # - ./site:/srv
      # Named volumes for persistent Caddy state (certs, etc.) and config backups
      - caddy_data:/data
      - caddy_config:/config

    environment:
      # Variables needed by Caddy (values sourced from ../.env via env_file)
      # Ensure these variable names EXACTLY match your ../.env file:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - ACME_EMAIL=${ACME_EMAIL}
      - TZ=${TZ:-Etc/UTC} # Use TZ from .env, default to UTC

    networks:
      # Connect to the shared external proxy network
      - proxy_network

    cap_add:
      # Required to bind ports 80/443 as non-root user inside container
      - NET_BIND_SERVICE

  ddclient:
    image: lscr.io/linuxserver/ddclient:latest
    container_name: ddclient
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      - PUID=${DEFAULT_PUID}
      - PGID=${DEFAULT_PGID}
      - TZ=${TZ}
      # Specific ddclient variables will be sourced from ../.env via env_file
      # Ensure DDCLIENT_CLOUDFLARE_EMAIL, DDCLIENT_CLOUDFLARE_API_TOKEN,
      # DDCLIENT_CLOUDFLARE_ZONE, DDCLIENT_CLOUDFLARE_RECORDS are set in .env
    volumes:
      - ./ddclient_config:/config # Persistent configuration for ddclient
    # network_mode: host # Option 1: If ddclient needs to directly see host's IP. Simpler for IP detection.
                         # This means it won't use the proxy_network.
                         # Ensure no port conflicts if other services use host network.
    networks:
      - proxy_network # Option 2: If ddclient can determine public IP via a check service (default for image).
                      # This keeps it on the defined network with Caddy.
    depends_on:
      - caddy # Optional: Start after Caddy, though not strictly dependent.

# Define the named volumes used by this service
volumes:
  caddy_data:
    driver: local # Or specify another driver if needed
  caddy_config:
    driver: local
  ddclient_config: # Named volume for ddclient configuration (if not using bind mount above)
    driver: local

# Define the shared network used by this service as external
networks:
  proxy_network:
    external: true
    name: proxy_network # Optional: Explicitly name it if it differs from the key
