# Docker Compose file for Portainer CE (Long Term Support version)
# Equivalent to:
# docker run -d -p 8000:8000 -p 9443:9443 --name portainer \
#   --restart=always -v /var/run/docker.sock:/var/run/docker.sock \
#   -v portainer_data:/data portainer/portainer-ce:lts

version: '3.8' # Use a modern version, '3' would also work here

services:
  portainer:
    image: portainer/portainer-ce:lts # Specifies the image to use
    container_name: portainer         # Sets the container name (--name)
    restart: always                   # Sets the restart policy (--restart=always)
    ports:                            # Defines port mappings (-p HOST:CONTAINER)
      - "8000:8000"                   # Portainer agent port (often optional)
      - "9443:9443"                   # Portainer Web UI (HTTPS) port
    volumes:                          # Defines volume mounts (-v HOST_PATH/VOLUME_NAME:CONTAINER_PATH)
      - /var/run/docker.sock:/var/run/docker.sock # Mounts the Docker socket
      - portainer_data:/data          # Mounts the named volume 'portainer_data' to /data inside

# Define named volumes used by services in this file
volumes:
  portainer_data: {} # Declares the named volume 'portainer_data'. '{}' uses the default driver (local).
